Repository gdsc-ssu/Path-to-Pet-Client, pull requests merged in 2024-02, with the labels that each got.

#5 메인화면 애니메이션 추가
  src/pages/Intro.jsx
Labels: Design 🎨

#12 [Feat] 유기동물등록 페이지
  .DS_Store
  src/.DS_Store
  src/App.jsx
  src/images/.DS_Store
  src/images/RegistDropPet.svg
  src/images/index.js
  src/pages/Registration.jsx
  src/pages/Select.jsx
Labels: Feat 💻, Design 🎨

#16 [Feat] 찾은 유기동물 등록 api 연동
  src/pages/Registration.jsx
  src/pages/Select.jsx
Labels: Feat 💻

#18 [refactor] css 수정 및 조회 이동 로직 변경
  src/components/AnimalCard.jsx
  src/components/DetailModal.jsx
  src/components/DetailModal2.jsx
  src/pages/Registration.jsx
  src/pages/Research.jsx
  src/pages/Select.jsx
Labels: Design 🎨, Refactor 🔄
